task_type: sl
project_name: sfgdsh
# 数据的存放路径
path_train: ''
path_dev: ''
path_test: ''
TextHeaders:
  text_a: 0 # 列的index从1开始,0 或者False 表示没有这一列
  text_b: 0
  label: 0 # 一般需要这个字段，并且不能改成其他名字
TaskInput:
  TextHasHeaders: True # txt文本是否有表头
  SentencesDelimiter: "\n" # 句子之间的分隔符,特殊字符注意用双引号
  ColumnDelimiter: "\t" # 列之间的分隔符, 特殊字符注意用双引号
  CharacterDelimiter: "\x02" # 字符之间的分隔符,用于NER等序列标注任务中, 特殊字符注意用双引号
  
  VocabFilePath: '' # 词典对应的地址,如果是pkl格式,会尝试解析为一个字典，否则需要人工编写函数
  LabelMapPath: '' # .json或者.pkl 保存的字典, 默认会用着两种方式进行解析
  FeaturePaddingStrOrInt: '' # padding用什么字符代替,可以是字符或者直接是id

Bert_config:
  bert_init_checkpoint_dir: ''


# 训练与测试参数
TrainParamaters:
  BatchSize: 16
  TotalStep: 10000
  EvaluateEveryStep: 100 # 多少个step进行打印
EvaluateParameters:
  BatchSize: 50
PredictParameters:
  BatchSize: 50




