task_type: {{task_type}}
project_name: {{project_name}}
TextHeaders:
  text_a: 0 # 列的index从1开始,0 或者False 表示没有这一列
  text_b: 0
  label: 0 # 一般需要这个字段，并且不能改成其他名字
TaskInput:
  TextHasHeaders: True # txt文本是否有表头
  SentencesDelimiter: "\n" # 句子之间的分隔符,特殊字符注意用双引号
  ColumnDelimiter: "\t" # 列之间的分隔符, 特殊字符注意用双引号
  {% if task_type == "sl" -%}
  CharacterDelimiter: "\x02" # 字符之间的分隔符,用于NER等序列标注任务中, 特殊字符注意用双引号
  {% endif %}

{% if tokenizer_type == "bert" -%}
bert_config:
  bert_init_checkpoint_dir: ''
{% endif %}
path_train:
path_dev:
path_test:

#model_params:




