task_type: sl
project_name: zx
TextHeaders:
  text_a: 0
  text_b: 0
  label: 0
TaskInput:
  TextHasHeaders: True # txt文本是否有表头
  SentencesDelimiter: "\n" # 句子之间的分隔符,特殊字符注意用双引号
  ColumnDelimiter: "\t" # 列之间的分隔符, 特殊字符注意用双引号
  CharacterDelimiter: "\x02" # 字符之间的分隔符,用于NER等序列标注任务中, 特殊字符注意用双引号
  

path_train:
path_dev:
path_test:

#model_params:



